export { default as Home } from "./Home";
export { default as MyPage } from "./MyPage/MyPage";
export { default as RankList } from "./MyPage/RankList";
export { default as EditNickname } from "./MyPage/EditNickname";
export { default as EditPassword } from "./MyPage/EditPassword";
export { default as Invest } from "./Invest";
export { MyAccount } from "./MyAccount";
export { default as Login } from "./Login/Login";
export { default as Landing } from "./Landing";
export { default as Register } from "./Register/Register";
export { default as Profile } from "./Register/Profile";
